name: Java CI

on:
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the build environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use Java 11

      - name: Build with Maven
        run: mvn clean install  # Build the project with Maven
